## Q1: 

In [96]:
x1=[0,1,0,1,0,1,0,1,1,1]
x2=[0,1,1,1,1,0,0,0,0,1]
x3=[1,0,1,1,0,1,1,0,1,1]
x4=[1,1,1,1,0,1,0,0,1,1]
x5=[0,0,1,0,0,1,0,0,0,1]

y=[-1,-1,-1,-1,-1,1,1,1,1,-1]

In [97]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
x1_encoded=le.fit_transform(x1)
x2_encoded=le.fit_transform(x2)
x3_encoded=le.fit_transform(x3)
x4_encoded=le.fit_transform(x4)
x5_encoded=le.fit_transform(x5)

In [98]:
# Converting string labels into numbers
label=le.fit_transform(y)

In [99]:
# Now combine both the features (weather and temp) in a single variable (list of tuples).

In [100]:
features=zip(x1_encoded,x2_encoded,x3_encoded,x4_encoded,x5_encoded)

In [101]:
# features=zip(weather_encoded,temp_encoded)
import numpy as np
features = np.array(list(zip(x1_encoded,x2_encoded,x3_encoded,x4_encoded,x5_encoded)))

In [102]:
for feature in features: print(feature)

[0 0 1 1 0]
[1 1 0 1 0]
[0 1 1 1 1]
[1 1 1 1 0]
[0 1 0 0 0]
[1 0 1 1 1]
[0 0 1 0 0]
[1 0 0 0 0]
[1 0 1 1 0]
[1 1 1 1 1]


In [103]:
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
wine = datasets.load_wine()

In [104]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set，70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(features, y, test_size=0.3,random_state=109)

In [105]:
print("len(X_train)=", len(X_train))
print("len(X_test)=", len(X_test))
print("len(y_train)=", len(y_train))
print("len(y_test)=", len(y_test))

len(X_train)= 7
len(X_test)= 3
len(y_train)= 7
len(y_test)= 3


In [106]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [107]:
#Predict the response for test dataset
y_pred = gnb.predict(X_test)

In [108]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0


## Q2:

In [109]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

model.fit(features,label)

GaussianNB(priors=None, var_smoothing=1e-09)

In [110]:
#Predict Output
predicted= model.predict([[0,0,0,0,0]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

Predicted Value: [1]


In [111]:
#Predict Output
predicted= model.predict([[1,1,0,1,0]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

Predicted Value: [0]
